server:
  port: 8082
  error:
    include-message: always

#postgres production database config
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: root
