server:
  port: 8082

spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: user-service
      port: 27017
      host: localhost
