server:
  port: 8082
  error:
    include-message: always

spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: user-service
      port: 27017
      host: localhost

jwt:
  private-key: "strongstrongstrongstrongstrongstrongstrongstrongstrongstrongstrongstrongstrongstrongstrongstrongstrongstrong"
  authorizationHeader: "Authorization"
  tokenPrefix: "Bearer "
  tokenExpirationAfterDays: 14
